apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: php:5.3-apache
        name: web
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html
          name: web-pv-claim
      restartPolicy: Always
      volumes:
      - name: web-pv-claim
        persistentVolumeClaim:
          claimName: web-pv-claim
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 80
     protocol: TCP
     name: http
  selector:
    app: web
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}